development:
  adapter: postgresql
  encoding: unicode
  database: phone_development
  pool: 5
  username: sample_postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: phone_test
  pool: 5
  username: sample_postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: phone_production
  pool: 5
  username: sample_postgres
  password:
